[package]
name = "retcon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
bytes = "1.1.0"
crossterm = "0.24.0"
prost = "0.10.4"
rustyline = "10.0.0"
tokio = { version = "1.20.0", features = ["full"] }

[build-dependencies]
prost-build = "0.10.4"
